[package]
name = "oracle-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = { version = "0.7.13", features = ["chrono"] }
postgres-types = { version = "0.2.9", features = ["chrono"] }
tokio = { version = "1.47", features = ["full"] }

serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

config = "0.15.14"
anyhow = "1.0.99"
thiserror = "2.0.15"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"