[package]
name = "oracle-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = "0.7.13"
postgres-types = "0.2.9"
tokio = { version = "1.47", features = ["full"] }

serde = { version = "1.0.219", features = ["derive"] }

config = "0.15.14"
anyhow = "1.0.99"
thiserror = "2.0.15"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
serde_json = "1.0.143"
num-bigint = { version = "0.4.6", features = ["serde"] }
axum = "0.8.4"
chrono = { version = "0.4", features = ["serde"] }
alloy = { version = "1.0.30", features = ["full"] }
alloy-provider = "1.0.30"
alloy-contract = "1.0.30"
alloy-transport-ws = "1.0.30"
alloy-primitives = "1.0.30"
alloy-sol-types = "1.0.30"
alloy-json-abi = "1.0.30"
alloy-dyn-abi = "1.0.30"
reqwest = "0.12.23"
dotenv = "0.15"
